import { yekan } from "@/utils/fonts";
import "./globals.css";
import Layout from "@/layout/Layout";
import NextAuthProvider from "@/providers/NextAuthProvider";

export const metadata = {
  title: "RealState Project",
  description: "Tutorial project for realstate, Generated by create next app",
  icons: {icon:"./favicon.ico"}
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="ltr">
      <body className={yekan.className}>
        <NextAuthProvider>
          <Layout>{children}</Layout>
        </NextAuthProvider>
      </body>
    </html>
  );
}
